exports.Users = [
  {
    id: 1,
    first_name: "Emi",
    last_name: "McCry",
    email: "emiMcCry@mail.com",
    gender: "female",
  },
  {
    id: 2,
    first_name: "feli",
    last_name: "Dry",
    email: "felidry@mail.com",
    gender: "female",
  },
  {
    id: 3,
    first_name: "Bali",
    last_name: "Fry",
    email: "balifry@mail.com",
    gender: "male",
  },
  {
    id: 4,
    first_name: "Emu",
    last_name: "Bye",
    email: "emubye@mail.com",
    gender: "male",
  },
  {
    id: 5,
    first_name: "Ali",
    last_name: "Pata",
    email: "alipata@gmail.com",
    gender: "male",
  },
  {
    id: 6,
    first_name: "Cali",
    last_name: "Dal",
    email: "calidal@mail.com",
    gender: "male",
  },
  {
    id: 7,
    first_name: "Dap",
    last_name: "Lol",
    email: "daplol@mail.com",
    gender: "male",
  },
  {
    id: 8,
    first_name: "Grace",
    last_name: "Lee",
    email: "gracelee@mail.com",
    gender: "female",
  },
  {
    id: 9,
    first_name: "Happy",
    last_name: "Birthday",
    email: "happybirthday@mail.com",
    gender: "male",
  },
  {
    id: 10,
    first_name: "Irene",
    last_name: "Haha",
    email: "irenehaha@mail.com",
    gender: "female",
  },
  {
    id: 11,
    first_name: "Jack",
    last_name: "O",
    email: "jacko@mail.com",
    gender: "male",
  },
  {
    id: 12,
    first_name: "Kim",
    last_name: "Poss",
    email: "kimposs@mail.com",
    gender: "female",
  },
  {
    id: 13,
    first_name: "Lola",
    last_name: "Talula",
    email: "lolatalula@mail.com",
    gender: "female",
  },
];
